name: Release
on: 
  release:
    types: [published]
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: 18
          distribution: 'temurin'

      - name: Set Version
        run: |
          sed "s/mod_version = 1.0/mod_version = ${{ github.event.release.tag_name }}/" -i gradle.properties

      - name: Build
        run: ./gradlew build
      
      - name: Publish
        uses: Kir-Antipov/mc-publish@v3.2
        with:

          name: Discount Stacking Fix v${{ github.event.release.tag_name }}
          game-versions: |
            1.19.4
            1.19.3
            1.19.2
            1.19.1
            1.19
            1.18.2
            1.18.1
            1.18
            1.17.1
            1.17
            1.16.5
            1.16.4
            1.16.3
            1.16.2
            1.16.1
            1.16
          loaders: |
            fabric
          java: |
            8

          modrinth-id: zhGm5cj4

          files-primary: build/libs/!(*-@(dev|sources|javadoc)).jar
          github-tag: ${{ github.event.release.tag_name }}
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          changelog: ${{ github.event.release.body }}